name: Build (release)
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install ufbt
        run: pipx install ufbt
      - name: Build
        run: ufbt build
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.fap
            dist/**/*.bin
