name: build-fap
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ufbt
        run: python -m pip install --upgrade pip && python -m pip install ufbt

      - name: Fetch SDK
        run: ufbt update

      - name: Debug tree
        run: |
          pwd
          ls -lah
          ls -lah protocols || true
          git ls-files | grep -i ble_spam_icons || true
          sed -n '1,120p' protocols/_base.h
        
      - name: Build
        run: APPID=magicband_plus_lights ufbt build

      - name: Upload .fap
        uses: actions/upload-artifact@v4
        with:
          name: magicband_plus_lights
          path: dist/*.fap
